name: Docker Image CI for GHCR

on:
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GHCR
        run: |
          docker login --username joanferrecid098 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
      - name: Build Image
        run: |
          docker build -t ghcr.io/joanferrecid098/pitolandia-bot:latest .
      - name: Push Image to GHCR
        run: |
          docker push ghcr.io/joanferrecid098/pitolandia-bot:latest
